Repository mehta-lab/VisCy, pull requests merged in 2024-06, with the labels that each got.

#84 Rename UNeXt2
  viscy/data/hcs.py
  viscy/light/engine.py
  viscy/scripts/count_flops.py
  viscy/scripts/network_diagram.py
  viscy/scripts/visualize_features.py
  viscy/unet/networks/fcmae.py
  viscy/unet/networks/unext2.py
Labels: documentation

#88 Test on Python 3.12
  .github/workflows/pr.yml
  pyproject.toml
Labels: maintenance, CI

#85 Add preprint reference to README
  README.md
Labels: documentation

#86 Fix architecture name in network diagram script
  viscy/scripts/network_diagram.py
Labels: bug

#89 Add the scale metadata to the output_stores
  viscy/light/predict_writer.py
Labels: enhancement

#94 Demo for VSCyto2D and VSCyto3D
  examples/demos/README.md
  examples/demos/demo_vscyto2d.py
  examples/demos/demo_vscyto3d.py
  examples/demos/demo_vsneuromast.py
  examples/demos/plot.py
Labels: documentation

#95 Fix demos on other platforms
  examples/demos/demo_vscyto2d.py
  examples/demos/demo_vscyto3d.py
  examples/demos/demo_vsneuromast.py
  viscy/data/hcs.py
  viscy/data/typing.py
Labels: bug, documentation

#96 README update
  README.md
  docs/figures/svideo_1.png
  docs/figures/svideo_3.png
  docs/figures/svideo_5.png
  docs/virtual_staining.md
Labels: documentation
