Repository mehta-lab/VisCy, pull requests merged in 2024-08, with the labels that each got.

#113 Single-cell phenotyping with contrastive learning
  applications/contrastive_phenotyping/graphs_ConvNeXt_ResNet.py
  applications/contrastive_phenotyping/pca.py
  applications/contrastive_phenotyping/predict.py
  applications/contrastive_phenotyping/profile_dataloader.py
  applications/contrastive_phenotyping/profile_dataloader.sh
  applications/contrastive_phenotyping/training_script.py
  viscy/data/hcs.py
  viscy/data/triplet.py
  viscy/data/typing.py
  viscy/light/engine.py
  viscy/representation/contrastive.py
  viscy/unet/networks/resnet.py
  viscy/unet/networks/unext2.py
Labels: enhancement

#126 Tune augmentations with CLI and config for contrastive models
  viscy/cli/contrastive_triplet.py
  viscy/data/triplet.py
  viscy/representation/__init__.py
  viscy/transforms.py
Labels: enhancement

#114 DLMBL 2024 notebook
  README.md
  examples/demos/README.md
  examples/virtual_staining/README.md
  examples/virtual_staining/VS_model_inference/demo_vscyto2d.py
  examples/virtual_staining/VS_model_inference/demo_vscyto3d.py
  examples/virtual_staining/VS_model_inference/demo_vsneuromast.py
  examples/virtual_staining/VS_model_inference/plot.py
  examples/virtual_staining/dlmbl_exercise/README.md
  examples/virtual_staining/dlmbl_exercise/convert-solution.py
  examples/virtual_staining/dlmbl_exercise/prepare-exercise.sh
  examples/virtual_staining/dlmbl_exercise/setup.sh
  examples/virtual_staining/dlmbl_exercise/solution.py
  examples/virtual_staining/img2img_translation/README.md
  examples/virtual_staining/img2img_translation/convert-solution.py
  examples/virtual_staining/img2img_translation/prepare-exercise.sh
  examples/virtual_staining/img2img_translation/setup.sh
  examples/virtual_staining/img2img_translation/solution.py
  pyproject.toml
Labels: documentation

#128 version lighting CLI example
  .gitignore
  applications/contrastive_phenotyping/demo_cli_fit.yml
  applications/contrastive_phenotyping/demo_cli_fit_slurm.sh
Labels: documentation

#131 Configurable drop path rate in contrastive models
  viscy/light/engine.py
  viscy/representation/contrastive.py
Labels: enhancement

#132 Config-based prediction with Xarray-based output format
  .gitignore
  applications/contrastive_phenotyping/contrastive_cli/fit.yml
  applications/contrastive_phenotyping/contrastive_cli/fit_slurm.sh
  applications/contrastive_phenotyping/contrastive_cli/plot_embeddings.py
  applications/contrastive_phenotyping/contrastive_cli/predict.yml
  applications/contrastive_phenotyping/contrastive_cli/predict_slurm.sh
  applications/contrastive_phenotyping/contrastive_scripts/demo_fit.py
  applications/contrastive_phenotyping/contrastive_scripts/graphs_ConvNeXt_ResNet.py
  applications/contrastive_phenotyping/contrastive_scripts/predict.py
  applications/contrastive_phenotyping/contrastive_scripts/predict_infection_score_supervised.py
  applications/contrastive_phenotyping/contrastive_scripts/profile_dataloader.py
  applications/contrastive_phenotyping/contrastive_scripts/profile_dataloader.sh
  applications/contrastive_phenotyping/contrastive_scripts/training_script.py
  applications/contrastive_phenotyping/profile_dataloader.py
  pyproject.toml
  viscy/data/triplet.py
  viscy/light/embedding_writer.py
  viscy/light/engine.py
  viscy/unet/networks/resnet.py
Labels: enhancement

#150 Remove obsolete scripts for contrastive phenotyping
  applications/contrastive_phenotyping/contrastive_scripts/demo_fit.py
  applications/contrastive_phenotyping/contrastive_scripts/predict.py
  applications/contrastive_phenotyping/contrastive_scripts/predict_infection_score_supervised.py
  applications/contrastive_phenotyping/contrastive_scripts/profile_dataloader.py
  applications/contrastive_phenotyping/contrastive_scripts/training_script.py
Labels: maintenance

#151 Fix deprecated custom forward method
  viscy/light/engine.py
Labels: maintenance

#145 SSL: fix MLP head and remove L2 normalization
  applications/contrastive_phenotyping/contrastive_cli/fit.yml
  applications/contrastive_phenotyping/contrastive_cli/plot_embeddings.py
  applications/contrastive_phenotyping/contrastive_cli/predict.yml
  applications/contrastive_phenotyping/contrastive_scripts/demo_fit.py
  applications/contrastive_phenotyping/contrastive_scripts/graphs_ConvNeXt_ResNet.py
  applications/infection_classification/classify_infection_covnext.py
  applications/infection_classification/predict_infection_classifier.py
  examples/configs/predict_example.yml
  examples/virtual_staining/VS_model_inference/demo_vscyto2d.py
  examples/virtual_staining/VS_model_inference/demo_vscyto3d.py
  examples/virtual_staining/VS_model_inference/demo_vsneuromast.py
  examples/virtual_staining/dlmbl_exercise/solution.py
  examples/virtual_staining/img2img_translation/solution.py
  tests/data/test_data.py
  tests/light/test_engine.py
  viscy/_log_images.py
  viscy/cli/cli.py
  viscy/cli/contrastive_triplet.py
  viscy/data/hcs.py
  viscy/representation/contrastive.py
  viscy/representation/embedding_writer.py
  viscy/representation/engine.py
  viscy/scripts/count_flops.py
  viscy/scripts/network_diagram.py
  viscy/scripts/visualize_features.py
  viscy/translation/engine.py
  viscy/translation/predict_writer.py
  viscy/translation/trainer.py
Labels: bug, enhancement, breaking
