Repository mehta-lab/VisCy, pull requests merged in 2024-07, with the labels that each got.

#103 Update dataset URL for demos
  examples/demos/demo_vscyto2d.py
  examples/demos/demo_vscyto3d.py
  examples/demos/demo_vsneuromast.py
Labels: documentation

#105 Bump lightning and matplotlib
  README.md
  pyproject.toml
Labels: maintenance

#70 Cellular infection phenotyping using annotated viral sensor data & label-free images
  applications/infection_classification/Infection_classification_25DModel.py
  applications/infection_classification/Infection_classification_2Dmodel.py
  applications/infection_classification/Infection_classification_covnextModel.py
  applications/infection_classification/classify_infection_25D.py
  applications/infection_classification/classify_infection_2D.py
  applications/infection_classification/classify_infection_covnext.py
  applications/infection_classification/infection_classifier_testing.py
  applications/infection_classification/predict_infection_classifier.py
  applications/infection_classification/readme.md
  pyproject.toml
  tests/preprocessing/test_pixel_ratio.py
  viscy/preprocessing/pixel_ratio.py
Labels: enhancement

#111 Pin numpy due to MONAI bug
  pyproject.toml
Labels: maintenance

#100 Updating demo notebook for training
  examples/demo_dlmbl/README.md
  examples/demo_dlmbl/convert-solution.py
  examples/demo_dlmbl/debug_log_graph.py
  examples/demo_dlmbl/setup.sh
  examples/demo_dlmbl/solution.py
  viscy/light/engine.py
Labels: documentation

#91 Test time augmentations
  viscy/data/ctmc_v1.py
  viscy/data/hcs.py
  viscy/light/engine.py
  viscy/light/predict_writer.py
Labels: enhancement

#112 Update demo setup script
  examples/demo_dlmbl/setup.sh
Labels: documentation
