Repository mehta-lab/VisCy, pull requests merged in 2024-10, with the labels that each got.

#184 Store UMAP embeddings in SSL predictions
  viscy/representation/embedding_writer.py
  viscy/representation/engine.py
  viscy/representation/evalutation/dimensionality_reduction.py
Labels: enhancement, representation

#186 Add representation section to readme
  README.md
  docs/figures/dynaCLR_schematic.png
Labels: documentation, representation

#189 Vendor pad shape function
  tests/translation/test_predict_writer.py
  viscy/translation/predict_writer.py
Labels: maintenance, translation

#190 Fix module name spelling
  applications/contrastive_phenotyping/evaluation/PC_vs_CF.py
  applications/contrastive_phenotyping/evaluation/PC_vs_CF_singleChannel.py
  applications/contrastive_phenotyping/evaluation/analyze_embeddings.py
  applications/contrastive_phenotyping/evaluation/cosine_similarity.py
  applications/contrastive_phenotyping/evaluation/displacement.py
  applications/contrastive_phenotyping/evaluation/grad_attr.py
  applications/contrastive_phenotyping/evaluation/linear_probing.py
  applications/contrastive_phenotyping/evaluation/log_regresssion_training.py
  applications/contrastive_phenotyping/evaluation/pca_umap_embeddings_time.py
  applications/contrastive_phenotyping/evaluation/plot_embeddings.py
  applications/contrastive_phenotyping/figures/classify_feb.py
  applications/contrastive_phenotyping/figures/classify_feb_embeddings.py
  applications/contrastive_phenotyping/figures/figure_cell_infection.py
  applications/contrastive_phenotyping/figures/save_patches.py
  applications/contrastive_phenotyping/figures/track_smoothness.py
  tests/representation/test_lca.py
  viscy/representation/embedding_writer.py
  viscy/representation/evaluation/__init__.py
  viscy/representation/evaluation/clustering.py
  viscy/representation/evaluation/dimensionality_reduction.py
  viscy/representation/evaluation/distance.py
  viscy/representation/evaluation/feature.py
  viscy/representation/evaluation/lca.py
Labels: bug, representation

#188 Add new author to citation
  CITATION.cff
Labels: documentation

#192 Add links to hosted files and napari-iohub wiki
  README.md
Labels: documentation, representation

#194 Bump MONAI to unpin NumPy
  pyproject.toml
Labels: maintenance

#197 Add badges to readme
  README.md
  pyproject.toml
Labels: documentation

#198 Simplify development installation
  .github/workflows/pr.yml
  CONTRIBUTING.md
  pyproject.toml
Labels: documentation, maintenance, CI
