Repository mehta-lab/VisCy, pull requests merged in 2025-08, with the labels that each got.

#281 Fix deprecated numpy call
  viscy/representation/evaluation/feature.py
Labels: maintenance, representation

#270 Expose Final Z cropping in TripletDataModule
  tests/data/test_triplet.py
  viscy/data/triplet.py
Labels: representation

#276 Batched dataloading for contrastive learning
  pyproject.toml
  viscy/cli.py
  viscy/data/combined.py
  viscy/data/triplet.py
  viscy/data/typing.py
  viscy/scripts/profiling.py
  viscy/transforms/__init__.py
  viscy/transforms/_redef.py
  viscy/transforms/_transforms.py
Labels: enhancement, representation

#284 Adding some batched transforms for MAE training
  viscy/transforms/__init__.py
  viscy/transforms/batched_rand_3d_elasticd.py
  viscy/transforms/batched_rand_flipd.py
  viscy/transforms/batched_rand_histogram_shiftd.py
  viscy/transforms/batched_rand_local_pixel_shufflingd.py
  viscy/transforms/batched_rand_sharpend.py
  viscy/transforms/batched_rand_zstack_shiftd.py
Labels: enhancement
