Repository mehta-lab/VisCy, pull requests merged in 2025-05, with the labels that each got.

#239 Add CLI tutorials for VCP
  examples/virtual_staining/vcp_tutorials/README.md
  examples/virtual_staining/vcp_tutorials/hek293t.ipynb
  examples/virtual_staining/vcp_tutorials/hek293t.py
Labels: documentation

#243 Update README.md to align with the title of the cytoland paper
  README.md
Labels: documentation

#244 Update VCP tutorials
  examples/virtual_staining/vcp_tutorials/hek293t.ipynb
  examples/virtual_staining/vcp_tutorials/hek293t.py
  examples/virtual_staining/vcp_tutorials/quick_start.ipynb
  examples/virtual_staining/vcp_tutorials/quick_start.py
Labels: documentation

#245 Delay cellpose import
  viscy/translation/engine.py
Labels: maintenance, translation

#248 Add contact information
  examples/virtual_staining/vcp_tutorials/hek293t.ipynb
  examples/virtual_staining/vcp_tutorials/hek293t.py
Labels: documentation

#249 Add neuromast notebook
  examples/virtual_staining/vcp_tutorials/neuromast.ipynb
  examples/virtual_staining/vcp_tutorials/neuromast.py
Labels: documentation

#252 Skip broken test with pycocotools on python 3.13
  tests/translation/test_evaluation.py
Labels: maintenance, CI

#251 Tweak VCP tutorials
  examples/virtual_staining/vcp_tutorials/hek293t.ipynb
  examples/virtual_staining/vcp_tutorials/hek293t.py
  examples/virtual_staining/vcp_tutorials/quick_start.ipynb
  examples/virtual_staining/vcp_tutorials/quick_start.py
Labels: documentation, translation
