Repository mehta-lab/VisCy, pull requests merged in 2025-09, with the labels that each got.

#289 add readthedocs config
  .readthedocs.yaml
Labels: documentation

#300 Adding annotation typings
  viscy/data/cell_classification.py
  viscy/data/typing.py
Labels: enhancement, representation

#305 Example for Shearing transform
  viscy/scripts/affine_shear_3dphatom_demo.py
Labels: documentation

#307 Patch ModelSummary with BatchTransforms
  viscy/data/combined.py
Labels: bug, representation
